---
- name: Instalacion de Docker y Docker Compose
  hosts: "{{ proyectname }}"
  become: true
  vars_files:
    - vars.yml  
  tasks:
    - name: Actualizar paquetes
      apt:
        update_cache: yes
      become: true

    - name: Instalar dependencias de Docker
      apt:
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
      become: true


    - name: Instalar Docker
      apt:
        name: docker.io
        state: latest
      become: true
      
    - name: Instalar Docker-compose
      apt:
        name: docker-compose
        state: latest
      become: true

    - name: Agregar usuario al grupo "docker"
      user:
        name: root
        groups: docker
        append: yes
      become: true

