---
- name: Despliegue de servicio con Docker Compose
  hosts: "{{ proyectname }}"
  vars_files:
    - vars.yml  
  become: true

  tasks:
    - name: Verificar si el directorio /docker existe
      stat:
        path: /docker
      register: docker_dir_check
      become: true

    - name: Crear directorio /docker si no existe
      file:
        path: /docker
        state: directory
      when: not docker_dir_check.stat.exists
      become: true

    - name: Copiar archivo docker-compose.yml
      copy:
        src: files/{{ proyectname  }}
        dest: /docker/
      become: true
      

    - name: Ejecutar Docker Compose
      command: docker-compose up -d
      args:
        chdir: /docker/{{ proyectname  }}
      become: true
