---
all:

    hosts:
        ansible:
            ansible_host: 192.168.10.25


    children:
        proxy_web:
            hosts:
                proxy_web_01:
                    ansible_host: 192.168.10.20
                    
                    
        jenkins:
            hosts:
                jenkins_01:
                    ansible_host: 192.168.10.28
        
        guacamole:
            hosts:
                guacamole_01:
                    ansible_host: 192.168.10.35



        glusterfs_cluster:
            hosts:
                glusterfs_01:
                    ansible_host: 192.168.10.30
                glusterfs_02:
                    ansible_host: 192.168.10.31
                    
                    
        vaultwarden:
            hosts:
                vaultwarden_01:
                    ansible_host: 192.168.10.34


        adguard:
            hosts:
                adguard_01:
                    ansible_host: 192.168.10.19


        DockerSwarm:
            hosts:
                DockerSwarm_01:
                    ansible_host: 192.168.10.41
                DockerSwarm_02:
                    ansible_host: 192.168.10.42
                DockerSwarm_03:
                    ansible_host: 192.168.10.43
                    
        LEMP-proyect:
            hosts:
                DockerSwarm_01:
                    proyect: 192.168.10.41