---
- name: Despliegue de servicio en Docker Swarm
  hosts: "{{ proyectname }}"
  vars_files:
    - vars.yml  
  become: true

  tasks:
  
  
    - name: Borramos posibles residuos Docker Compose
      command: docker stop mariadb nginx php ; docker rm mariadb nginx php
      become: true
      ignore_errors: yes
  
  
    - name: Ejecutar Docker Compose
      command: docker-compose up -d
      args:
        chdir: /docker/{{ proyectname  }}
      become: true

